- name: yum install for Apache Web Server
  yum: name=httpd state=latest
  with_items:
    - httpd

- name: Start to Apache
  service: name=httpd enabled=yes

- name: Start to Apache
  service: name=httpd state=started

- name: Change the httpd.conf to template file ( Apache 2.2 )
  copy: src=httpd22.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 6
  notify: restart httpd

- name: Change the httpd.conf to template file ( Apache 2.4 )
  copy: src=httpd24.conf dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat' and ansible_distribution_version.split('.')[0]|int == 7
  notify: restart httpd

- name: Makes to Defalut Virtual Host
  template: src=_default_.conf dest=/etc/httpd/conf.d/_default_.conf
  notify: restart httpd

- name: Makes to Default DocumentRoot
  file: path=/var/www/_default_ state=directory owner=root group=root mode=0755

- name: Makes to Virtual Host
  template: src=virtualhost.conf dest=/etc/httpd/conf.d/{{ item.domain }}.conf
  with_items:
    - "{{ site }}"
  notify: restart httpd

- name: Makes to DocumentRoot
  file: path=/var/www/{{ item.domain }} state=directory owner={{ item.owner }} group={{ item.owner }} mode=0755
  with_items:
    - "{{ site }}"
