#- name: (Initialize) Firewalld stopped ( CentOS 7 )
#  service: name=firewalld state=stopped enabled=no

- name: (Initialize) Locale setting ( CentOS 7 )
#  shell: localectl set-locale LANG=ja_JP.UTF-8
  replace: dest="/etc/locale.conf" regexp='^LANG=en_US\.UTF-8' replace='LANG=ja_JP.UTF-8'

TASK [common : (Kaizen-Operation) CloudWatch Logs Default Stoped] **************
- name: (Initialize) SELinux desabled initialize
  yum: name=libselinux-python state=latest

- name: (Initialize) SELinux desabled
  selinux: state=disabled
  register: st

- name: reboot if SELinux changed
  shell: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: st.changed

- name: waiting for server to reboot
  wait_for: host="{{ ansible_ssh_host | default(inventory_hostname) }}" port={{ ansible_ssh_port | default(22) }} search_regex=OpenSSH delay=30 timeout=120
  connection: local
  become: false
  when: st.changed
