- name: yum install for ftp
  yum: name={{ item }} state=latest
  with_items:
    - vsftpd
    - mod_ssl
  notify: restart vsftpd

- name: Start to vsftpd
  service: name=vsftpd enabled=yes

- name: Start to vsftpd
  service: name=vsftpd state=started

- name: Chanfed vsftpd.conf
  template: src=vsftpd.conf dest=/etc/vsftpd/ owner=root group=root mode=0600
  notify: restart vsftpd
